Add support for directory and file detection
IonicaBizau/node-is-there pull request #20
Opened 2017-01-26 04:18 UTC by petrgazarov

Hey @IonicaBizau, this PR adds `directory()` and `file()` to check if they exist.

I nested existing functionality under `path()`, so now it has the following three methods:

`directory()`
`file()`
`path()`

It is a breaking change, and you would probably want to bump the major version. Once reviewed, happy to make appropriate changes to README. Thanks!

Closes #19

2017-01-26 07:51 UTC, IonicaBizau requested changes
Overall, it looks good, but instead of exporting an object, let's export the function like it used to be, but adding the `file` and `directory` methods to that function value.

Then we can do:

```js
const isThere = require("is-there");
isThere();
isThere.file();
isThere.directory();
```

2017-02-04 00:54 UTC, petrgazarov commented
Hey @IonicaBizau, I updated it to be a function. One caveat - JSDoc shows the `new` keyword for the class. It seemed like the best option to display this information, but let me know if you have a better idea. Thanks!

2017-02-05 05:15 UTC, IonicaBizau requested changes
Overall, looks good, just some small changes. Thank you very much!

2017-02-05 05:15 UTC, IonicaBizau commented on lib/index.js
> +var IsThere = (function() {
I think there's no need for this wrapping function (unless you have a good reason).

2017-02-05 05:15 UTC, IonicaBizau commented on lib/index.js
> +   * @class IsThere
I'm pretty sure my docs generator will not like this `@class` thingy. Let's change it into `@function`.

2017-02-05 05:15 UTC, IonicaBizau commented on lib/index.js
> +  var IsThere = function(path, callback) {
Use `const IsThere`. Maybe, with this occasion, change everywhere `IsThere` into `isThere` (lowercase).

2017-02-05 05:15 UTC, IonicaBizau commented on lib/index.js
> +  /**
Can you add here the name of the function (`directory`) and the description after it, on a new line?

2017-02-05 05:15 UTC, IonicaBizau commented on lib/index.js
> +   * @function file
Same here, add the name + description.

2017-02-09 05:06 UTC, petrgazarov commented
@IonicaBizau Thanks for review. One comment -- I spent an hour changing jsdoc around, and from that the `@class` + `@memberOf` were the clearest when rendered (with the small exception of the `new` keyword, see my comment above).

I can change all three to be plain functions with name + description but they are all going to be on the same level. I'm not sure if this is desirable.

**This is how it looks if they are all functions with `@name` + `@description`:**

![jsdoc__home](https://cloud.githubusercontent.com/assets/5581195/22770014/e1936a3a-ee5a-11e6-81f6-b48a698a68ef.png)

*************************************************************************
**Here is how it looks with the `@class`:**

![jsdoc__home](https://cloud.githubusercontent.com/assets/5581195/22770033/1078070c-ee5b-11e6-9ed2-3d3d4ee2aec1.png)
*************************************************************************
![jsdoc__class__isthere](https://cloud.githubusercontent.com/assets/5581195/22770049/276cc574-ee5b-11e6-8f5a-e021629b22a2.png)

2017-02-09 09:15 UTC, merged

2017-02-09 09:15 UTC, IonicaBizau commented
Currently I don't really have this kind of fancy docs pages. The docs are generated using [`blah`](https://github.com/IonicaBizau/blah).

This is how I do it: https://ionicabizau.net/blog/33-how-i-npm